version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hms
    ports:
      - '3307:3306'
    volumes:
      - ./hms.sql:/docker-entrypoint-initdb.d/hms.sql
